config/routes.rb
Madutualang::Application.routes.draw do
  resources :purchases

  resources :customers
  devise_for :agents
  resources :agents

  root :to => "pages#index"	

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :customers	
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :aktif, :alamat, :daerah, :nama, :negeri, :no_kp, :pengurus, :tarikh_mula, :umur, :poskod
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :agent
  has_many :purchases
  
  attr_accessible :aktif, :alamat, :daerah, :nama, :negeri, :no_kp, :penyakit, :poskod, :tarikh_mula, :umur, :agent_id
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :customer
  attr_accessible :agent_id, :customer_id, :kuantiti, :produk, :tarikh_belian
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_filter :authenticate_agent!
  
  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
	@customers = current_agent.customers
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agents }
    end
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    @agent = Agent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/new
  # GET /agents/new.json
  def new
    @agent = Agent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/1/edit
  def edit
    @agent = Agent.find(params[:id])
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(params[:agent])

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render json: @agent, status: :created, location: @agent }
      else
        format.html { render action: "new" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agents/1
  # PUT /agents/1.json
  def update
    @agent = Agent.find(params[:id])

    respond_to do |format|
      if @agent.update_attributes(params[:agent])
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent = Agent.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
	if current_agent.pengurus == 1
	  @customers = Customer.all
	  @agents = Agent.all
	else
	  @customers = current_agent.customers
	end	

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = current_agent.customers.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  # GET /purchases
  # GET /purchases.json
  def index
	@agents = Agent.all
	@all_customers = Customer.all
	if params[:customer_id].nil?
	  @purchases = Purchase.all
	else
	  @customer = Customer.find(params[:customer_id])
	  @purchases = @customer.purchases
	end
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchases }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
	@agents = Agent.all
    @purchase = Purchase.find(params[:id])
	@customer = Customer.find(@purchase.customer_id)
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new
	@customer = Customer.find(params[:customer_id])
    @purchase = Purchase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/1/edit
  def edit
    @purchase = Purchase.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
	@customer = Customer.find(params[:purchase][:customer_id])
    @purchase = @customer.purchases.new(params[:purchase])
	@purchase[:agent_id] = current_agent.id

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render json: @purchase, status: :created, location: @purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchases/1
  # PUT /purchases/1.json
  def update
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      if @purchase.update_attributes(params[:purchase])
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %>
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :no_kp %>
    <%= f.text_field :no_kp %>
  </div>
  <div class="field">
    <%= f.label :umur %>
    <%= f.text_field :umur %>
  </div>
  <div class="field">
    <%= f.label :alamat %>
    <%= f.text_field :alamat %>
  </div>
  <div class="field">
    <%= f.label :negeri %>
    <%= f.text_field :negeri %>
  </div>
  <div class="field">
    <%= f.label :daerah %>
    <%= f.text_field :daerah %>
  </div>
  <div class="field">
    <%= f.label :poskod %>
    <%= f.text_field :poskod %>
  </div>  
  <div class="field">
    <%= f.label :tarikh_mula %>
    <%= f.date_select :tarikh_mula %>
  </div>
  <div class="field">
    <%= f.label :aktif %>
    <%= f.number_field :aktif %>
  </div>
  <!--  
  <div class="field">
    <%#= f.label :pengurus %>
    <%#= f.number_field :pengurus %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Kemaskini maklumat agen</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<% if current_agent.pengurus == 1 %>
	<h1>Senarai Agen Berdaftar</h1>
	<br />
	<table class="table table-bordered table-hover">
	  <tr>
		<th>Nama</th>
		<th>No KP</th>
		<th>Negeri</th>
		<th>Daerah</th>
		<th>Aktif</th>
		<th>Pengurus</th>
		<th></th>
		<th></th>
		<th></th>
	  </tr>
	<% @agents.each do |agent| %>
	  <tr>
		<td><%= agent.nama %></td>
		<td><%= agent.no_kp %></td>
		<td><%= agent.negeri %></td>
		<td><%= agent.daerah %></td>
		<% if agent.aktif == 1 %>
			<td> Ya </td>
		<% elsif agent.aktif == 0 %>
			<td> Tidak </td>
		<% else %>
			<td> Belum diproses </td>
		<% end %>
		<% if agent.pengurus == 1 %>
			<td> Ya </td>
		<% else %>
			<td> Tidak </td>
		<% end %>
		<td><%= link_to "Info", agent %></td>
		<td><%= link_to "Edit", edit_agent_path(agent) %></td>
		<td><%= link_to "Hapus", agent, method: :delete, data: { confirm: "Are you sure?" } %></td>
	  </tr>
	<% end %>
	</table>

	<br />
	<%= link_to "Lihat senarai pelanggan anda", customers_path %>
<% elsif current_agent.aktif == 0 %>
	<p>
		Terima kasih kerana mendaftar dengan syarikat Madu Tualang. Pihak kami akan memproses pendaftaran anda dalam tempoh 3 hari bekerja. 
	</p>
<% elsif current_agent.aktif == 1 %>
	<%= link_to "Lihat senarai pelanggan anda", customers_path %>
<% end %>

app/views/agents/new.html.erb
<h1>New agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nama:</b>
  <%= @agent.nama %>
</p>

<p>
  <b>No kp:</b>
  <%= @agent.no_kp %>
</p>

<p>
  <b>Umur:</b>
  <%= @agent.umur %>
</p>

<p>
  <b>Alamat:</b>
  <%= @agent.alamat %>
</p>

<p>
  <b>Negeri:</b>
  <%= @agent.negeri %>
</p>

<p>
  <b>Daerah:</b>
  <%= @agent.daerah %>
</p>

<p>
  <b>Poskod:</b>
  <%= @agent.poskod %>
</p>

<p>
  <b>Tarikh mula:</b>
  <% if @agent.tarikh_mula.nil? %>
	<%= time_tag @agent.created_at %>
  <% else %>
	<%= @agent.tarikh_mula %>
  <% end %>
</p>

<p>
  <b>Aktif:</b>
  <% if @agent.aktif == 1 %>
	Ya
  <% elsif @agent.aktif == 0 %>
	Tidak
  <% else %>
	Belum diproses
  <% end %>
</p>

<p>
  <b>Pengurus:</b>
  <% if @agent.pengurus == 1 %>
	Ya
  <% else %>
	Tidak
  <% end %>
</p>


<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :nama %>
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :no_KP %>
    <%= f.text_field :no_kp %>
  </div>
  <div class="field">
    <%= f.label :umur %>
    <%= f.text_field :umur %>
  </div>
  <div class="field">
    <%= f.label :alamat %>
    <%= f.text_field :alamat %>
  </div>
  <div class="field">
    <%= f.label :negeri %>
    <%= f.text_field :negeri %>
  </div>
  <div class="field">
    <%= f.label :daerah %>
    <%= f.text_field :daerah %>
  </div>
  <div class="field">
    <%= f.label :poskod %>
    <%= f.text_field :poskod %>
  </div>
  <div class="field">
    <%= f.label :penyakit %>
    <%= f.text_field :penyakit %>
  </div>
  <div class="field">
    <%= f.label :tarikh_mula %>
    <%= f.date_select :tarikh_mula %>
  </div>
  <div class="field">
    <%= f.label :aktif %>
    <%= f.number_field :aktif %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Senarai pelanggan berdaftar</h1><br />
<table class="table table-bordered table-hover">
  <tr>
	<% if current_agent.pengurus == 1 %>
	<th>Agen</th>
	<% end %>
    <th>Nama</th>
    <th>Negeri</th>
	<th>Daerah</th>
    <th>Penyakit</th>
    <th>Tarikh mula</th>
    <th>Aktif</th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
	<% if current_agent.pengurus == 1 %>
	<td><%= @agents.find{|a| a["id"] == customer.agent_id }.nama %></td>
	<% end %>
    <td><%= link_to customer.nama, customer %></td>
    <td><%= customer.negeri %></td>
    <td><%= customer.daerah %></td>
    <td><%= customer.penyakit %></td>
    <td><%= customer.tarikh_mula %></td>
    <td>
	<% if customer.aktif == 1 %>
	  Ya
	<% else %>
	  Tidak
	<% end %>
	</td>
    <td><%= link_to "Edit", edit_customer_path(customer) %></td>
    <td><%= link_to "Hapus", customer, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Tambah pelanggan", new_customer_path %>

app/views/customers/new.html.erb
<h1>Maklumat pelanggan baru</h1><br />

<%= render "form" %>

<%= link_to "Back", agents_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nama:</b>
  <%= @customer.nama %>
</p>

<p>
  <b>No KP:</b>
  <%= @customer.no_kp %>
</p>

<p>
  <b>Umur:</b>
  <%= @customer.umur %>
</p>

<p>
  <b>Alamat:</b>
  <%= @customer.alamat %>
</p>

<p>
  <b>Negeri:</b>
  <%= @customer.negeri %>
</p>

<p>
  <b>Daerah:</b>
  <%= @customer.daerah %>
</p>

<p>
  <b>Poskod:</b>
  <%= @customer.poskod %>
</p>

<p>
  <b>Penyakit:</b>
  <%= @customer.penyakit %>
</p>

<p>
  <b>Tarikh mula:</b>
  <%= @customer.tarikh_mula %>
</p>

<p>
  <b>Aktif:</b>
  <% if @customer.aktif == 1 %>
	Ya
  <% else %>
    Tidak
  <% end %>	
</p>

<%= link_to "Rekod belian", purchases_path(:customer_id => @customer.id) %> |
<%= link_to "Edit", edit_customer_path(@customer) %> |
<%= link_to "Back", customers_path %>

app/views/layouts/_header.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>		
			<a class="brand" href="<%= root_path %>">Madu Tualang</a>
			<ul class="nav">
				<li><a href="<%= root_path %>">Halaman Utama</a></li>
				<li class="divider-vertical"></li>
				<li><a href="#">Khasiat Madu Tualang</a></li>
				<li class="divider-vertical"></li>
				<li><a href="#">Hubungi Kami</a></li>
				<li class="divider-vertical"></li>
			</ul>
			<form class="navbar-form pull-right">
			<input type="text" class="span2">
			<button type="submit" class="btn">Search</button>
			</form>
			<ul class="nav pull-right">
				<li class="divider-vertical"></li>
				<% if agent_signed_in? %>
					<li>
						<%= link_to "Log out", destroy_agent_session_path, :method => :delete %>
					</li>
				<% else %>
					<li class="dropdown">	
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Log In <b class="caret"></b></a> 
						<ul class="dropdown-menu">
							<li><a href="<%= agents_path %>">Agent Log In</a></li>
						</ul>
					</li>	
				<% end %>
				<li class="divider-vertical"></li>		
			</ul>
		</div>
	</div>
</div>
<div style="width;100%; height:200px; background-color:#A6D6EE; margin-top:-20px; margin-bottom:20px;">	
</div>

app/views/layouts/_sidenav.html.erb
<ul class="nav nav-tabs nav-stacked">
	<% if agent_signed_in? %>
	<li>
		<%= link_to "Senarai agen berdaftar", agents_path %>
	</li>
	<li>
		<%= link_to "Senarai pelanggan berdaftar", customers_path %>
	</li>
		<% if current_agent.pengurus == 1 %>
		<li>
			<%= link_to "Senarai belian produk terbaru", purchases_path %>
		</li>
		<% end %>	
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Madutualang</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span2">
					<%= render "layouts/sidenav" %>
				</div>
				<div class="span10">
					<%= yield %>
				</div>
		</div>
	<%= render "layouts/footer" %>
</body>
</html>

app/views/pages/index.html.erb
<h1>Madu Tualang</h1>
<br/>
<h4>Khasiat</h4>
	<p>Antara khasiat .................</p>
<h4>Asal Usul</h4>
	<p>Madu berasal dari ....... Syarikat Madu Tualang memastikan semua madu yang dibekalkan berada pada kualiti yang terbaik 
	dan melepasi piawaian yang ditetapkan.</p>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :produk %>
    <%= f.text_field :produk %>
  </div>
  <div class="field">
    <%= f.label :kuantiti %>
    <%= f.number_field :kuantiti %>
  </div>
  <div class="field">
    <%= f.label :tarikh_belian %>
    <%= f.date_select :tarikh_belian %>
  </div>
  <input class="hidden" id="purchase_customer_id" name="purchase[customer_id]" size="30" type="text" value="<%= @customer.id %>" />
  <div class="actions">
    <%= f.submit(:customer_id => @customer.id) %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%#= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>
Senarai belian 
<% if @customer.nil? %>
	<small>(<%= @purchases.count %>)</small>
<% else %>
	<small><%= @customer.nama %></small>
<% end %>
</h1><br />

<table class="table table-bordered table-hover">
  <tr>
    <th>Produk</th>
    <th>Kuantiti</th>
    <th>Tarikh belian</th>
    <th>Agent</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchases.each do |purchase| %>
  <tr>
    <td><%= purchase.produk %></td>
    <td><%= purchase.kuantiti %></td>
    <td><%= purchase.tarikh_belian %></td>
    <td><%= @agents.find{|a| a["id"] == purchase.agent_id }.nama %></td>
    <% if @customer.nil? %>
		<td><%= @all_customers.find{|a| a["id"] == purchase.customer_id }.nama %></td>
	<% else %>
		<td><%= @customer.nama %></td>	
	<% end %>
    <td><%= link_to "Info", purchase %></td>
    <td><%= link_to "Edit", edit_purchase_path(purchase) %></td>
    <td><%= link_to "Hapus", purchase, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br />
<% if @customer.nil? %>
<% else %>
<%= link_to "Tambah belian baru", new_purchase_path(:customer_id => @customer.id) %>
<% end %>

app/views/purchases/new.html.erb
<h1>Belian baru <small><%= @customer.nama %></small></h1>

<%= render 'form' %>

<%#= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Produk:</b>
  <%= @purchase.produk %>
</p>

<p>
  <b>Kuantiti:</b>
  <%= @purchase.kuantiti %>
</p>

<p>
  <b>Tarikh belian:</b>
  <%= @purchase.tarikh_belian %>
</p>

<p>
  <b>Agent:</b>
  <%= @agents.find{|a| a["id"] == @purchase.agent_id }.nama %>
</p>

<p>
  <b>Customer:</b>
  <%= @customer.nama %>
</p>


<%= link_to "Edit", edit_purchase_path(@purchase) %> |
<%= link_to "Back", purchases_path(:customer_id => @customer.id) %>